version: '3.3'
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - /var/lib/postgresql/data

  mysql:
    platform: linux/x86_64 # use for mac M1
    image: mysql:8.0.26
    restart: always
    container_name: mysql
    environment:
     MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    
  mongodb:
    image: mongo:5
    restart: always
    container_name: mongodb
    volumes:
      - ./mongodb:/data/db
    ports:
      - '27017:27017'
