version: '3.3'
services:
  mysql:
    platform: linux/amd64 # use for mac M1
    image: mysql:8.0
    restart: always
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    
  mongodb:
    image: mongo:5
    restart: always
    container_name: mongodb
    volumes:
      - ./mongodb:/data/db
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password